"""empty message

Revision ID: 56a0b5815838
Revises: f801446b1a80
Create Date: 2022-12-04 17:45:23.033343

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '56a0b5815838'
down_revision = 'f801446b1a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.create_unique_constraint("tmp", ['email'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("tmp", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
