"""empty message

Revision ID: f801446b1a80
Revises: c6b03b9454b3
Create Date: 2022-12-04 16:39:02.889563

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f801446b1a80'
down_revision = 'c6b03b9454b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
                              existing_type=sa.REAL(),
                              type_=sa.Float(precision=2),
                              existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(length=80),
                              type_=sa.String(length=256),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.String(length=256),
                              type_=sa.VARCHAR(length=80),
                              existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
                              existing_type=sa.Float(precision=2),
                              type_=sa.REAL(),
                              existing_nullable=False)

    # ### end Alembic commands ###
